version: "3.2"
services:

  huawei-solar-rtu:
    container_name: huawei-solar-rtu-v4
    restart: always
    image: gasiepgodoy/integracao-geracao-solar:v0.0.4
    user: root
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - INVERTER_PORT=/dev/ttyUSB0
      - MQTT_HOST=186.217.146.134
      - BROKER_PORT=1883
      - USE_CREDENTIALS=NO
      - USER_NAME=unesp.sorocaba
      - PASSWORD=smart.campus
      - MQTT_TOPIC=smartcampus/solar
      - DATA_MODE=INVERTER # INVERTER or OFFLINE
